### ISSUE TITLE
Consider to add fallback for @import

### ISSUE THREAD

**Issue by timaschew** [jonathantneal/postcss-partial-import#12]
Looks little bit strange to me that all my `@import` statements now looking **only** for files with an underscore if I use this plugin.

Consider to provide a fallback to search for the origin filename to avoid throwing an error.

**Comment by TrySound** [comment]
@timaschew Yes. You forgot to read documentation.
https://github.com/jonathantneal/postcss-partial-import#prefix

**Comment by timaschew** [comment]
I would assume that this plugin will try to find the file with an underscore and if its not there it will try the file without an underscore instead of throwing an error.

This plugins just breaks the CSS standard, `@import`.

**Comment by TrySound** [comment]
Use only one pack if you don't want to break something. Also `postcss-cssnext` do not include `postcss-import`.

**Comment by timaschew** [comment]
Just don't understand why its not fallback to the origin name

**Comment by TrySound** [comment]
It's functionality of plugin.

**Comment by timaschew** [comment]
Okay, I changed the issue title to consider to change the functionality.

**Comment by jonathantneal** [comment]
@timaschew, I agree with your desired functionality completely. This plugin should already work that way, exactly. It will only add the prefix and suffix if your css url does not include a file extension. So, `@import url(myfile.css)` works as expected while `@import url(myfile)` uses `_myfile.css`. If it does not do this, then there is a bug.

Furthermore, there is a standing issue to also search `bower_modules` and `node_modules`. The only reason I have not added these is because I have yet to figure out how to work with the caching functionality that is in this plugin. It was written by a great developer who made the PR for it, and it’s a little too complicated for me.

**Comment by jonathantneal** [comment]
I have added in the later functionality in v2 :)
