### ISSUE TITLE
Use webpack resolver and its aliases?

### ISSUE THREAD

**Issue by FezVrasta** [jonathantneal/postcss-partial-import#31]
Seems like this plugin doesn't allow to use the webpack resolver to resolve the import paths. Is there a way?

**Comment by jonathantneal** [comment]
Would you provide more details? I cannot resolve this without more information.

**Comment by FezVrasta** [comment]
Example:


```sass
// src/components/foobar/index.css
@import 'src/components/foobaz/index.css;
```

will look for `components/foobar/src/components/foobaz/foobaz.css`

But inside my webpack I have a `src` alias that points to `__dirname/src/` so I would expect to respect this alias and resolve it to `src/components/foobaz/index.css`

**Comment by jonathantneal** [comment]
This isn’t something configurable with postcss-partial-import or postcss-import? If not, since this plugin now relies on postcss-import, you may want to file an issue there and ask them if it can be repaired at the source. Here are the postcss-import options, though you should have access to them all via postcss-partial-import https://github.com/postcss/postcss-import#options

**Comment by FezVrasta** [comment]
I didn't know this plugin was based on the other one. thank you, I'll look around
